apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: backup-yaml
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/sanjid133/kubectl-backup-yaml/releases/download/v0.1.0/backup-yaml_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./backup-yaml"
      to: "."
    - from: LICENSE
      to: "."
    bin: "backup-yaml"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/sanjid133/kubectl-backup-yaml/releases/download/v0.1.0/backup-yaml_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./backup-yaml"
      to: "."
    - from: LICENSE
      to: "."
    bin: "backup-yaml"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/sanjid133/kubectl-backup-yaml/releases/download/v0.1.0/backup-yaml_windows_amd64.zip
    sha256: ""
    files:
    - from: "/backup-yaml.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "backup-yaml.exe"
  shortDescription: A new plugin
  homepage: https://github.com/sanjid133/kubectl-backup-yaml
  caveats: |
    Usage:
      $ kubectl backup-yaml

    For additional options:
      $ kubectl backup-yaml --help
      or https://github.com/sanjid133/kubectl-backup-yaml/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
